name: AdvancedMining
version: ${project.version}
main: fr.gohansword.advancedmining.AdvancedMining
api-version: 1.16
authors: [ GohanSword ]
commands:
  oremenu:
    description: ???
    aliases: [om, orem]